### ISSUE TITLE
Reverse API calls to turn into standalone client.

### ISSUE THREAD

**Issue by arturohernandez10** [sidoh/epaper_templates#46]
It would be nice to turn this into a full HATEOAS REST implementation. So that users could use the pen of some ePapers. The simplest way I can think of is to create a hook, which could receive the template and the coordinates of the click. And in turn respond with JSON equivalent to an API call. Perhaps `{url:'/api/v1/variables', verb:'PUT', payload:{...}}`. While also having a way to refresh all the templates with a remote server. The idea is to have a standalone client to which a single URL could be added and voila. A remote server would completely control the device.

**Comment by sidoh** [comment]
Sorry for the stupidly late reply here, @arturohernandez10. This one slipped through the cracks.

the project is presently pretty coupled with GxEPD2, which only supports Waveshare displays (don't think Waveshare makes any touch displays), but certainly open to expanding that.

Going to close this for now because it's out of the scope I see this project having for the foreseeable future, but very open to collaborating with someone!
